### ISSUE TITLE
fill in missing fns, namespaces from Functional Differential Geometry

### ISSUE THREAD

**Issue by sritchie** [sicmutils/sicmutils#325]
Namespaces remaining in `calculus`:

- [x] SR-boost.scm (#339)
- [x] SR-frames.scm (#339 )
- [x] frame-maker.scm (#339)
- [x] indexed.scm (#339)
- [x] tensors.scm (#339)
- [x] ode.scm (#339)
- [x] vector-calculus.scm (#339)
- [x] gram-schmidt.scm (#339)
- [x] hodge-star.scm (#339)
- [x] metric.scm (#338)
- [x] connection.scm (#338)
- [x] curvature.scm (#337)
- [x] Lie.scm (#328, lives in covariant.cljc)
- [x] basis.scm
- [x] coord.scm
- [x] covariant-derivative.scm (#328)
- [x] dgutils.scm
- [x] exterior-derivative.scm (#328)
- [x] form-fields.scm (#328)
- [x] interior-product.scm (#328, look in covariant.cljc)
- [x] manifold.scm
- [x] maps.scm (#328)
- [x] vector-fields.scm (#328)
- [x] wedge.scm (#328)

Here's what's missing, usually just from `sicmutils.env`, not from the full library. This is up to page 95 so far in [the pdf](http://xahlee.info/math/i/functional_geometry_2013_sussman_14322.pdf).

- metric, literal-metric, metric->components, metric->Christoffel-2
- coordinates, velocities
- define-coordinates, paired with let-coordinates
- procedure->vector-field (not aliased in env)
- make-operator
- series:for-each, series:sum (we have these for sure, right??)
- change oneform-field to 1form-field?
- note `s:map/r` is `s/mapr`
- note pullback == pullback-function from scm... alias!
- pullback-vector-field, pullback-form
- F->directional-derivative, F-lie needs to be exposed

**Comment by sritchie** [comment]
Forgot to note that we have them all!
