### ISSUE TITLE
add moments monoid, fold to sicmutils.statistics.moments

### ISSUE THREAD

**Issue by sritchie** [sicmutils/sicmutils#452]
As good a place as any. Here is the code, thanks to [`MomentsGroup`](https://github.com/twitter/algebird/blob/develop/algebird-core/src/main/scala/com/twitter/algebird/MomentsGroup.scala) from Algebird and http://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Parallel_algorithm.

Just needs tests and a home. Related to #427.

### TODO

- [ ] investigate `scmutils.numerics.statistics.moments` to see if there is anything we are missing. Read up on sample vs population variance, see about our -1.
- [ ] also this one for online https://www.johndcook.com/blog/standard_deviation/
- [ ] add john cook reference https://www.johndcook.com/blog/skewness_kurtosis/
- [ ] implement running regression ALSO in statistics, after we get this working! https://www.johndcook.com/blog/running_regression
- [ ] covariance fold, monoid, batched-fold described here: https://en.wikipedia.org/wiki/Algorithms_for_calculating_variance#Covariance, and maybe here https://github.com/twitter/algebird/blob/100086a26db188603e677e8a23b79418d75aa08a/algebird-core/src/main/scala/com/twitter/algebird/CorrelationMonoid.scala

**Comment by sritchie** [comment]
From https://www.johndcook.com/blog/2013/06/11/computing-skewness-and-kurtosis-in-one-pass/, sample skewness and kurtosis:

```
double RunningStats::SkewnessCS() const
{
// Calculate the population skewness:
double g = sqrt(double(n)) * M3/ pow(M2, 1.5);
// Return the corrected sample skewness:
return sqrt( double(n*n-1))*g / double(n-2);
}

double RunningStats::KurtosisCS() const
{
// Calculate the population excess kurtosis
double g = double(n)*M4 / (M2*M2) – 3.0;
// Return the corrected sample excess kurtosis
return double(n-1) / double( (n-2)*(n-3) ) * ( double(n+1)*g + 6 );
}
```

**Comment by sritchie** [comment]
Closing in favor of sicmutils/sicmutils#454 .
